CREATE DATABASE IF NOT EXISTS JOINS;

USE JOINS;


CREATE TABLE COMPANY4
(
	Sno INT PRIMARY KEY,
    Candidate_Name VARCHAR(30)
);
INSERT INTO COMPANY4
VALUES 
	(1,"Sanjay"),
    (2,"Venkat"),
    (3,"Satish"),
    (4,"Rahul");
     
SELECT * FROM COMPANY4;